Windows build: Add DLL build targets
aws/aws-cdi-sdk pull request #26
Opened 2021-01-04 15:03 UTC by kebby

This PR adds two build targets to the Windows build to compile the SDK as a dynamic library instead of  a static one, and a batch file to build a binary distribution from the DLL Release build.

As to why - while binary compatibility under Windows is pretty much perfect, maintaining static libraries can become a hellish nightmare. If a static library doesn't use the exact same platform tool set, SDK version and build flavor as whatever tries to link to it, you're in for a lot of weird and subtle bugs. This can also mean having to recompile 3rd party static libraries when there's an SDK update, and all kinds of other maintenance shenanigans.

Thus, I added build configurations that compile the CDI SDK as a DLL which, when you add libfabric and the aws-cpp-sdk dlls, only has dependencies that are built into Windows 10, and are stable. Building the SDK is now only necessary when the SDK itself is updated.

In detail there are the following changes:
- Changed the #ifdef in cdi_utility_api.h to _WIN32 with an underscore because that one's a compiler built-in, and WIN32 wasn't set
- Added CDI_INTERFACE to all public API declarations where it was missing, plus those internal APIs that are used by cdi_test and the examples
- Added explicit dependency from cdi_sdk to libfabric in the project
- Added Release_DLL and Debug_DLL build targets to the solution and cdi_* projects. cdi_sdk will be compiled as DLL in those configurations. pdcurses and libfabric aren't changed.
- Added custom build step (for the _DLL targets) to copy all libfabric related files to the correct output directory so debugging works

As a bonus (I can take those things out of the PR if you want to)
- wrote a deployment script (proj/make_distrib.bat) that copies all necessary files from the Release_DLL config (bin, include, lib, docs) into a target directory (build/aws-cdi-sdk) for distribution in binary form
- turned on multi processor compilation for all cdi_* projects (really helps)
- cleaned up the headers section in the VC project, and the VC related parts of .gitignore

It would be appreciated to get this PR into mainline because it really helps with our own workflow. We're using a lot of 3rd party libraries and integrations, and not having to maintain them build wise unless there's a necessary update is a lot of time saved.

2021-01-04 22:01 UTC, trevorheaws requested changes
Thank you for the submission. I have posted a number of comments flagging spots where line length exceeds 120 characters. I have created an internal task for us to detail our our code formatting conventions in a publicly accessible document. Thank you for your patience on this and the high quality contribution.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_baseline_profile_api.h
> +CDI_INTERFACE bool CdiAvmParseBaselineVersionString(const char* version_str, CdiAvmBaselineProfileVersion* ret_version_ptr);
We have cut an internal ticket to add a project style guide to our project. In the mean time we limit column width to 120 characters. So please split this onto a second line.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_logger_api.h
> +CDI_INTERFACE bool CdiLoggerCreateFileLog(CdiLoggerHandle logger_handle, const char* filename_str, CdiLogHandle* ret_log_handle_ptr);
Split to a second line to keep line length below 120 characters.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_logger_api.h
> +                                           const char* function_name_str, int line_number, CdiLogMultilineState* state_ptr);
line length again.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_os_api.h
> +CDI_INTERFACE bool CdiOsThreadCreatePinned(ThreadFuncName thread_func, CdiThreadID* thread_id_out_ptr, const char* thread_name_str,
Split lines to avoid going over 120 characters per line.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_os_api.h
> +CDI_INTERFACE bool CdiOsSignalsWait(CdiSignalType* signal_array, uint8_t num_signals, bool wait_all, uint32_t timeout_in_ms,
Adjust lines so that they stay under 120 characters.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_os_api.h
> +CDI_INTERFACE bool CdiOsSplitPath(const char* filepath_str, char* filename_str, int filename_buf_size, char* directory_str,
Line length

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_pool_api.h
> +CDI_INTERFACE bool CdiPoolCreate(const char* name_str, uint32_t item_count, uint32_t grow_count, uint32_t max_grow_count,
Keep line length under 120.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_pool_api.h
> +CDI_INTERFACE bool CdiPoolCreateUsingExistingBufferAndInitItems(const char* name_str, uint32_t item_count, uint32_t item_byte_size,
Line length again. This function name is so long it definitely makes this area a bit clunky but still would like to keep to the line length.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_pool_api.h
> +CDI_INTERFACE bool CdiPoolForEachItem(CdiPoolHandle handle, CdiPoolItemOperatorFunction operator_function, const void* context_ptr);
Line length again.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_queue_api.h
> +CDI_INTERFACE bool CdiQueueCreate(const char* name_str, uint32_t item_count, uint32_t grow_count, uint32_t max_grow_count,
Make line length less than or equal to 120 characters per line.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_queue_api.h
> +CDI_INTERFACE bool CdiQueuePopWait(CdiQueueHandle handle, int timeout_ms, CdiSignalType abort_wait_signal, void* item_dest_ptr);
Line length again.

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_queue_api.h
> +CDI_INTERFACE bool CdiQueuePushWait(CdiQueueHandle handle, int timeout_ms, CdiSignalType abort_wait_signal, const void* item_ptr);
line length

2021-01-04 22:01 UTC, trevorheaws commented on include/cdi_queue_api.h
> +CDI_INTERFACE bool CdiQueuePushWaitMultiple(CdiQueueHandle handle, int timeout_ms, CdiSignalType* abort_wait_signal_array,
line length

2021-01-04 22:01 UTC, trevorheaws commented on src/common/include/fifo_api.h
> +CDI_INTERFACE bool CdiFifoCreate(const char* name_str, int item_count, int item_byte_size, CdiFifoFullCallback full_cb_ptr,
line length.

2021-01-04 22:01 UTC, trevorheaws commented on src/common/include/fifo_api.h
> +CDI_INTERFACE bool CdiFifoRead(CdiFifoHandle handle, int timeout_ms, CdiSignalType abort_wait_signal, void* item_dest_ptr);
line length

2021-01-04 22:01 UTC, trevorheaws commented on src/common/include/fifo_api.h
> +CDI_INTERFACE bool CdiFifoWrite(CdiFifoHandle handle, int timeout_ms, CdiSignalType abort_wait_signal, const void* item_ptr);
line length

2021-01-05 13:07 UTC, kebby commented
Ok, line lengths are fixed, and there was also a hiccup with the project file thanks to my git ineptitude but that should be good now, too.

Thanks for considering this PR, this really saves us a lot of work.

2021-01-05 16:33 UTC, trevorheaws approved these changes
Thank you for making the line length changes.

2021-01-05 20:27 UTC, merged